---
apiVersion: v1
kind: Namespace
metadata:
  name: stardew-test

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stardew-server
  namespace: stardew-test
  labels:
    app: stardew-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stardew-server
  template:
    metadata:
      labels:
        app: stardew-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: lagranx86

      tolerations:
      - key: "node.kubernetes.io/disk-pressure"
        operator: "Exists"
        effect: "NoSchedule"

      containers:
      - name: stardew-server
        image: raigeiki55/stardoods-test-1:latest
        imagePullPolicy: Always

        ports:
        - name: game
          containerPort: 24642
          protocol: UDP
        - name: vnc
          containerPort: 5800
          protocol: TCP
        - name: vnc-ws
          containerPort: 5900
          protocol: TCP

        env:
        # Replace with your Steam credentials
        - name: STEAM_USER
          value: "YOUR_STEAM_USERNAME_HERE"
        - name: STEAM_PASS
          value: "YOUR_STEAM_PASSWORD_HERE"
        # VNC password for web interface
        - name: VNC_PASSWORD
          value: "changeme"
        # Display settings
        - name: DISPLAY_WIDTH
          value: "1280"
        - name: DISPLAY_HEIGHT
          value: "720"

        volumeMounts:
        - name: game-data
          mountPath: /data

        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"

      volumes:
      - name: game-data
        hostPath:
          path: /data/stardew-test
          type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: stardew-server
  namespace: stardew-test
  labels:
    app: stardew-server
spec:
  type: NodePort
  selector:
    app: stardew-server
  ports:
  - name: game
    port: 24642
    targetPort: 24642
    protocol: UDP
  - name: vnc-web
    port: 5800
    targetPort: 5800
    protocol: TCP
  - name: vnc
    port: 5900
    targetPort: 5900
    protocol: TCP
