---
apiVersion: v1
kind: Namespace
metadata:
  name: stardew-test

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stardew-data
  namespace: stardew-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # Optional: specify storageClassName if you have a specific storage class
  # storageClassName: local-path

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stardew-config
  namespace: stardew-test
data:
  # Steam credentials (replace with your actual credentials or use secrets)
  STEAM_USER: "your_steam_username"
  # VNC settings
  VNC_PASSWORD: "changeme"
  DISPLAY_WIDTH: "1280"
  DISPLAY_HEIGHT: "720"
  # Game settings
  GAME_PORT: "24642"

---
apiVersion: v1
kind: Secret
metadata:
  name: stardew-secrets
  namespace: stardew-test
type: Opaque
stringData:
  # IMPORTANT: Replace with your actual Steam password
  # Or better yet, create this secret separately with: kubectl create secret generic stardew-secrets --from-literal=steam-password='your_password' -n stardew-test
  steam-password: "your_steam_password_here"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stardew-server
  namespace: stardew-test
  labels:
    app: stardew-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stardew-server
  template:
    metadata:
      labels:
        app: stardew-server
    spec:
      # Optional: Node selector for lagranx86
      nodeSelector:
        kubernetes.io/hostname: lagranx86

      # Optional: Toleration for disk pressure
      tolerations:
      - key: "node.kubernetes.io/disk-pressure"
        operator: "Exists"
        effect: "NoSchedule"

      containers:
      - name: stardew-server
        image: raigeiki55/stardoods-test-1:latest
        imagePullPolicy: Always

        ports:
        - name: game
          containerPort: 24642
          protocol: UDP
        - name: vnc
          containerPort: 5800
          protocol: TCP
        - name: vnc-ws
          containerPort: 5900
          protocol: TCP

        env:
        - name: STEAM_USER
          valueFrom:
            configMapKeyRef:
              name: stardew-config
              key: STEAM_USER
        - name: STEAM_PASS
          valueFrom:
            secretKeyRef:
              name: stardew-secrets
              key: steam-password
        - name: VNC_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: stardew-config
              key: VNC_PASSWORD
        - name: DISPLAY_WIDTH
          valueFrom:
            configMapKeyRef:
              name: stardew-config
              key: DISPLAY_WIDTH
        - name: DISPLAY_HEIGHT
          valueFrom:
            configMapKeyRef:
              name: stardew-config
              key: DISPLAY_HEIGHT

        volumeMounts:
        - name: game-data
          mountPath: /data

        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"

      volumes:
      - name: game-data
        persistentVolumeClaim:
          claimName: stardew-data

---
apiVersion: v1
kind: Service
metadata:
  name: stardew-server
  namespace: stardew-test
  labels:
    app: stardew-server
spec:
  type: NodePort
  selector:
    app: stardew-server
  ports:
  - name: game
    port: 24642
    targetPort: 24642
    protocol: UDP
    # Optional: specify nodePort if you want a specific port
    # nodePort: 30642
  - name: vnc-web
    port: 5800
    targetPort: 5800
    protocol: TCP
    # nodePort: 30800
  - name: vnc
    port: 5900
    targetPort: 5900
    protocol: TCP
    # nodePort: 30900
